//Get all categories
GET http://localhost:8080/categories

###
// Get all categories of one user
GET http://localhost:8080/categories/user/6268e3d12dd3c5ad708838d7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjhlM2QxMmRkM2M1YWQ3MDg4MzhkNyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjUxMzc1ODkzLCJleHAiOjE2NTE5ODA2OTN9.Gnaw2shZxiKLtxwxUgNYk3DcMXWVU_nNi64yfLtsoVE

###
// Create one
POST http://localhost:8080/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjhlM2QxMmRkM2M1YWQ3MDg4MzhkNyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjUxMzc1ODkzLCJleHAiOjE2NTE5ODA2OTN9.Gnaw2shZxiKLtxwxUgNYk3DcMXWVU_nNi64yfLtsoVE
Content-Type: application/json

{
    "name": "Entries"
}

###
// Update one

PATCH http://localhost:8080/categories/626dff26cbf4ae45b0948418
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjhlM2QxMmRkM2M1YWQ3MDg4MzhkNyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjUxMzc1ODkzLCJleHAiOjE2NTE5ODA2OTN9.Gnaw2shZxiKLtxwxUgNYk3DcMXWVU_nNi64yfLtsoVE
Content-Type: application/json

{
    "name": "To Do"
}

###
// Delete one

DELETE http://localhost:8080/categories/626dba5daf305a05b8abc97b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjhlMmM1ZjRmZGY0YTU0YThkZDVkMSIsImVtYWlsIjoianhvcnRpejE1QGdtYWlsLmNvbSIsImlhdCI6MTY1MTM1NzI0MCwiZXhwIjoxNjUxOTYyMDQwfQ.JgLt-8hTz2em5RbKdJ0zNiS-NZaiouvmddxfM2gay2U