// Get all entries
GET http://localhost:8080/entries

###
// Get one entry
GET http://localhost:8080/entries/626655c1e294ade6a26acf71

###
// Create entry
POST http://localhost:8080/entries
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjhlM2QxMmRkM2M1YWQ3MDg4MzhkNyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjUxMDQ2MTEwfQ.SfJHmx_opWSUUBLRIiOGsHJhwHJmyR6_CgpEhNfxNSU",
    "title": "Entry 06", 
    "body": "Admin posting"    
}
 
###
// Delete entry
DELETE http://localhost:8080/entries/62688baf4c46ebefa7d1ad49

###
// Update entry
PATCH http://localhost:8080/entries/6266578be294ade6a26acf78
Content-Type: application/json

{
    "title": "Entry 02"
}

