// Get all entries
GET http://localhost:8080/entries

###
// Get one entry
GET http://localhost:8080/entries/626655c1e294ade6a26acf71

###
// Create entry
POST http://localhost:8080/entries
Content-Type: application/json

{
    "title": "Entry 03", 
    "body": "I started developing a full-stack web app for diaries. I'm actually learning a lot, despite the fact that I am speedrunning these modules so I can get this database up and running already."    
}
 
###
// Delete entry
DELETE http://localhost:8080/entries/62688baf4c46ebefa7d1ad49

###
// Update entry
PATCH http://localhost:8080/entries/6266578be294ade6a26acf78
Content-Type: application/json

{
    "title": "Entry 02"
}

