// Get all users
GET http://localhost:8080/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjhlM2QxMmRkM2M1YWQ3MDg4MzhkNyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjU0NDczMjA3LCJleHAiOjE2NTUwNzgwMDd9.sFyYNTht7X88_j-icdmqGlgCdKpuKco-bHI2qovOVSs

###
// Get one user
GET http://localhost:8080/users/6268e2c5f4fdf4a54a8dd5d1

###

// Create new user
POST http://localhost:8080/users
Content-Type: application/json

{
    "email": "delete@gmail.com",
    "username": "delete", 
    "password": "password"
}
 
###
// Update user
PATCH http://localhost:8080/users/6268e3d12dd3c5ad708838d7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjhlM2QxMmRkM2M1YWQ3MDg4MzhkNyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjU5MjI5ODI2LCJleHAiOjE2NTk4MzQ2MjZ9.ayfPtrN-rS8z45Q9qOeQCiyyLZ6g6reNYsuI_m5rqbU

{
    "password": "december15",
    "bio": "Developer of Entries"
}

###
// Delete user
DELETE  http://localhost:8080/users/626daef8da54dce26ee0cd57
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjhlMmM1ZjRmZGY0YTU0YThkZDVkMSIsImVtYWlsIjoianhvcnRpejE1QGdtYWlsLmNvbSIsImlhdCI6MTY1MTE2MjM5NSwiZXhwIjoxNjUxNzY3MTk1fQ.py9Nj5pIm3KKd7rvPCmxZD-ekV9qaZIcBV1o5ood6cY

###
// Login testing

POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "password"
}